version: '3.8'

services:
  web:
    restart: unless-stopped
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne conversa_dj.asgi:application --bind 0.0.0.0 --port 8000 -v2
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    links:
      - redis
    depends_on:
      - db
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - chatApp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  chatApp_postgres_data:
  static_volume:
  media_volume: